### ISSUE TITLE
Error: not opened - Exception should be handled inside the lib to avoid the process from crashing

### ISSUE THREAD

**Issue by realtime-framework** [realtime-framework/RealtimeMessaging-Node#7]
Error: not opened
    at WebSocket.send (project\node_modules\ws\lib\WebSocket.js:219:16)
    at WebSocket.ortc.sockjs.onmessage (project\node_modules\ibtrealtimesjnode\IbtRealTimeSJNode.js:1455:65)

**Comment by realtime-framework** [comment]
Published version 2.1.29-beta for further testing before merging into master
